// Localized structural strings for the generated notebook, so its headings and
// labels match the learner's selected UI language. Pure (only a type import from
// i18n) and deterministic: the locale is passed in, not read from global state,
// so the generator stays unit-testable. Agent-written prose (synthesis,
// summaries) is localized separately via the review-language setting.

import type { Locale } from "../i18n.js";

export type NotebookLabels = {
  generatedNote: string;
  updated: string;
  indexIntro: string;
  rebuildNote: string;
  newHerePrefix: string;
  newHereSuffix: string;
  chapters: string;
  noChapters: string;
  /** "{n} documents" */
  documentsCount: string;
  pages: string;
  noPages: string;
  /** "{n} annotations" */
  annotationsCount: string;
  synthesis: string;
  documentContext: string;
  source: string;
  concepts: string;
  none: string;
  annotationsLabel: string;
  originalTextIndex: string;
  noExcerpt: string;
  annotationContent: string;
  note: string;
  review: string;
  dialogueContext: string;
  you: string;
  tutor: string;
  seeAlso: string;
  notebookName: string;
  aboutName: string;
  /** "Documents related through the concept **{concept}**." */
  relatedThrough: string;
  documents: string;
  learningSummaryName: string;
  summaryIntro: string;
  strengths: string;
  weaknesses: string;
  methods: string;
  grasped: string;
  revisit: string;
  declarationTitle: string;
  declaration: string[];
};

const en: NotebookLabels = {
  generatedNote: "Generated by Annotation Tutor Lite. Rebuildable; do not maintain manually.",
  updated: "Updated",
  indexIntro: "Your study notebook, built from annotations and tutor dialogue.",
  rebuildNote: "Rebuildable from the Build notebook command — edits here are overwritten.",
  newHerePrefix: "New here? Open ",
  newHereSuffix: " for the format and the ideas behind it.",
  chapters: "Chapters",
  noChapters: "No related-document chapters yet.",
  documentsCount: "{n} documents",
  pages: "Pages",
  noPages: "No studied documents yet. Annotate a note to begin.",
  annotationsCount: "{n} annotations",
  synthesis: "Synthesis",
  documentContext: "Document context",
  source: "Source",
  concepts: "Concepts",
  none: "None",
  annotationsLabel: "Annotations",
  originalTextIndex: "Original text index",
  noExcerpt: "(no excerpt)",
  annotationContent: "Annotation content",
  note: "Note",
  review: "Review",
  dialogueContext: "Dialogue context",
  you: "You",
  tutor: "Tutor",
  seeAlso: "See also",
  notebookName: "Notebook",
  aboutName: "About this notebook",
  relatedThrough: "Documents related through the concept **{concept}**.",
  documents: "Documents",
  learningSummaryName: "Learning summary",
  summaryIntro: "Your strengths, weaknesses, and problem-solving methods, distilled from your memory cells.",
  strengths: "Strengths",
  weaknesses: "Weaknesses",
  methods: "Problem-solving methods",
  grasped: "What you grasped",
  revisit: "What to revisit",
  declarationTitle: "About This Notebook",
  declaration: [
    "> What this notebook is, the ideas behind it, and how to use it.",
    "",
    "## What it is",
    "",
    "A study companion built automatically from your annotations, the tutor's reviews, your in-margin dialogues, and the memory cells distilled from them. Your source notes stay the source of truth — rebuild any time.",
    "",
    "## How to open it",
    "",
    "Click the notebook icon in the left ribbon (Open study notebook), or run **Open study notebook** from the command palette. Run **Build notebook** to refresh, or **Enrich notebook with agent** for AI summaries.",
    "",
    "## Format",
    "",
    "- The index (Notebook) is your entry point.",
    "- pages/: one page per studied document — context, an original-text index, your annotations + reviews, and your dialogue.",
    "- chapters/: documents grouped by a shared concept.",
    "",
    "## The ideas behind it",
    "",
    "- Zettelkasten: documents are literature notes; the chapters and index are structure notes linking ideas across sources.",
    "- Active recall & the Feynman technique: explaining a passage in your own words exposes and then closes the gaps.",
    "- Socratic questioning: the tutor nudges with questions, not just verdicts.",
    "- Spaced repetition (SM-2 / Ebbinghaus forgetting curve): memory cells are scheduled for review before you forget them.",
    "",
    "## Why it helps",
    "",
    "One private, searchable place that shows what you've engaged with in your own words, surfaces connections between sources, and keeps it ready for review.",
    ""
  ]
};

const zhCn: NotebookLabels = {
  generatedNote: "由 Annotation Tutor Lite 生成，可重建，请勿手动维护。",
  updated: "更新于",
  indexIntro: "你的学习笔记本，由批注与助手对话生成。",
  rebuildNote: "可通过“生成笔记本”命令重建——此处的改动会被覆盖。",
  newHerePrefix: "初次使用？打开 ",
  newHereSuffix: " 了解格式与理念。",
  chapters: "章节",
  noChapters: "暂无相关文档章节。",
  documentsCount: "{n} 篇文档",
  pages: "页面",
  noPages: "还没有学习过的文档。先为一篇笔记添加批注。",
  annotationsCount: "{n} 条批注",
  synthesis: "综述",
  documentContext: "文档背景",
  source: "来源",
  concepts: "概念",
  none: "无",
  annotationsLabel: "批注",
  originalTextIndex: "原文索引",
  noExcerpt: "（无摘录）",
  annotationContent: "批注内容",
  note: "笔记",
  review: "点评",
  dialogueContext: "对话记录",
  you: "你",
  tutor: "助手",
  seeAlso: "另见",
  notebookName: "笔记本",
  aboutName: "关于本笔记本",
  relatedThrough: "通过概念 **{concept}** 相关联的文档。",
  documents: "文档",
  learningSummaryName: "学习总结",
  summaryIntro: "根据你的记忆单元提炼出的优势、薄弱点与解题方法。",
  strengths: "优势",
  weaknesses: "薄弱点",
  methods: "解题方法",
  grasped: "已掌握",
  revisit: "需复习",
  declarationTitle: "关于本笔记本",
  declaration: [
    "> 本笔记本是什么、背后的理念，以及如何使用。",
    "",
    "## 这是什么",
    "",
    "一个自动生成的学习伙伴，来源于你的批注、助手点评、批注框内对话，以及由它们提炼出的记忆单元。你的源笔记始终是最终依据——可随时重建。",
    "",
    "## 如何打开",
    "",
    "点击左侧边栏的笔记本图标（打开学习笔记本），或在命令面板中运行 **打开学习笔记本**。运行 **生成笔记本** 可刷新，运行 **用助手丰富笔记本** 可添加 AI 综述。",
    "",
    "## 格式",
    "",
    "- 索引（笔记本）是你的入口。",
    "- pages/：每篇学习过的文档一页——背景、原文索引、你的批注与点评，以及对话。",
    "- chapters/：按共同概念归类的文档。",
    "",
    "## 背后的理念",
    "",
    "- 卡片盒（Zettelkasten）：文档是文献笔记；章节与索引是连接各来源观点的结构笔记。",
    "- 主动回忆与费曼技巧：用自己的话解释一段内容，能暴露并弥补理解的缺口。",
    "- 苏格拉底式提问：助手以提问引导，而非只给结论。",
    "- 间隔复习（SM-2 / 艾宾浩斯遗忘曲线）：在你遗忘之前，为记忆单元安排复习。",
    "",
    "## 它的好处",
    "",
    "一个私密、可搜索的地方，用你自己的话呈现你学过的内容，浮现来源之间的关联，并随时供你复习。",
    ""
  ]
};

const zhTw: NotebookLabels = {
  generatedNote: "由 Annotation Tutor Lite 產生，可重建，請勿手動維護。",
  updated: "更新於",
  indexIntro: "你的學習筆記本，由註解與助手對話產生。",
  rebuildNote: "可透過「產生筆記本」命令重建——此處的變更會被覆寫。",
  newHerePrefix: "初次使用？開啟 ",
  newHereSuffix: " 了解格式與理念。",
  chapters: "章節",
  noChapters: "尚無相關文件章節。",
  documentsCount: "{n} 篇文件",
  pages: "頁面",
  noPages: "還沒有學習過的文件。先為一篇筆記新增註解。",
  annotationsCount: "{n} 條註解",
  synthesis: "綜述",
  documentContext: "文件背景",
  source: "來源",
  concepts: "概念",
  none: "無",
  annotationsLabel: "註解",
  originalTextIndex: "原文索引",
  noExcerpt: "（無摘錄）",
  annotationContent: "註解內容",
  note: "筆記",
  review: "點評",
  dialogueContext: "對話紀錄",
  you: "你",
  tutor: "助手",
  seeAlso: "另見",
  notebookName: "筆記本",
  aboutName: "關於本筆記本",
  relatedThrough: "透過概念 **{concept}** 相關聯的文件。",
  documents: "文件",
  learningSummaryName: "學習總結",
  summaryIntro: "根據你的記憶單元提煉出的優勢、弱點與解題方法。",
  strengths: "優勢",
  weaknesses: "弱點",
  methods: "解題方法",
  grasped: "已掌握",
  revisit: "需複習",
  declarationTitle: "關於本筆記本",
  declaration: [
    "> 本筆記本是什麼、背後的理念，以及如何使用。",
    "",
    "## 這是什麼",
    "",
    "一個自動產生的學習夥伴，來自你的註解、助手點評、註解框內對話，以及由它們提煉出的記憶單元。你的來源筆記始終是最終依據——可隨時重建。",
    "",
    "## 如何開啟",
    "",
    "點選左側邊欄的筆記本圖示（開啟學習筆記本），或在命令面板執行 **開啟學習筆記本**。執行 **產生筆記本** 可重新整理，執行 **用助手豐富筆記本** 可加入 AI 綜述。",
    "",
    "## 格式",
    "",
    "- 索引（筆記本）是你的入口。",
    "- pages/：每篇學習過的文件一頁——背景、原文索引、你的註解與點評，以及對話。",
    "- chapters/：依共同概念歸類的文件。",
    "",
    "## 背後的理念",
    "",
    "- 卡片盒（Zettelkasten）：文件是文獻筆記；章節與索引是連接各來源觀點的結構筆記。",
    "- 主動回憶與費曼技巧：用自己的話解釋一段內容，能暴露並彌補理解的缺口。",
    "- 蘇格拉底式提問：助手以提問引導，而非只給結論。",
    "- 間隔複習（SM-2 / 艾賓浩斯遺忘曲線）：在你遺忘之前，為記憶單元安排複習。",
    "",
    "## 它的好處",
    "",
    "一個私密、可搜尋的地方，用你自己的話呈現你學過的內容，浮現來源之間的關聯，並隨時供你複習。",
    ""
  ]
};

const ja: NotebookLabels = {
  generatedNote: "Annotation Tutor Lite が生成。再生成可能のため手動で編集しないでください。",
  updated: "更新",
  indexIntro: "注釈とチューターとの対話から作られた学習ノートブックです。",
  rebuildNote: "「ノートブックを作成」コマンドで再生成できます。ここでの編集は上書きされます。",
  newHerePrefix: "はじめての方は ",
  newHereSuffix: " で形式と考え方をご覧ください。",
  chapters: "チャプター",
  noChapters: "関連文書のチャプターはまだありません。",
  documentsCount: "{n} 件の文書",
  pages: "ページ",
  noPages: "学習した文書がまだありません。まずノートに注釈を付けてください。",
  annotationsCount: "{n} 件の注釈",
  synthesis: "まとめ",
  documentContext: "文書の背景",
  source: "出典",
  concepts: "概念",
  none: "なし",
  annotationsLabel: "注釈",
  originalTextIndex: "原文インデックス",
  noExcerpt: "（抜粋なし）",
  annotationContent: "注釈の内容",
  note: "メモ",
  review: "講評",
  dialogueContext: "対話の記録",
  you: "あなた",
  tutor: "チューター",
  seeAlso: "関連",
  notebookName: "ノートブック",
  aboutName: "このノートブックについて",
  relatedThrough: "概念 **{concept}** でつながる文書。",
  documents: "文書",
  learningSummaryName: "学習サマリー",
  summaryIntro: "メモリセルから抽出した、あなたの強み・弱み・問題解決の方法。",
  strengths: "強み",
  weaknesses: "弱み",
  methods: "問題解決の方法",
  grasped: "理解できたこと",
  revisit: "復習すべきこと",
  declarationTitle: "このノートブックについて",
  declaration: [
    "> このノートブックの内容、背景にある考え方、使い方。",
    "",
    "## これは何か",
    "",
    "あなたの注釈・チューターの講評・余白での対話、そしてそこから抽出されたメモリセルから自動的に作られる学習の相棒です。元のノートが常に正となり、いつでも再生成できます。",
    "",
    "## 開き方",
    "",
    "左のリボンのノートブックアイコン（学習ノートブックを開く）をクリックするか、コマンドパレットで **学習ノートブックを開く** を実行します。**ノートブックを作成** で更新、**エージェントでノートブックを充実** で AI まとめを追加できます。",
    "",
    "## 形式",
    "",
    "- インデックス（ノートブック）が入口です。",
    "- pages/：学習した文書ごとに 1 ページ——背景、原文インデックス、注釈と講評、対話。",
    "- chapters/：共通の概念でまとめた文書。",
    "",
    "## 背景にある考え方",
    "",
    "- Zettelkasten：文書は文献ノート、チャプターとインデックスは出典をまたいで考えをつなぐ構造ノート。",
    "- 能動的想起とファインマン・テクニック：自分の言葉で説明することで理解の穴が見え、埋まります。",
    "- ソクラテス式の問い：チューターは結論だけでなく問いで促します。",
    "- 間隔反復（SM-2 / エビングハウスの忘却曲線）：忘れる前にメモリセルの復習を予定します。",
    "",
    "## 役立つ理由",
    "",
    "学んだ内容を自分の言葉で見渡せ、出典間のつながりが浮かび上がり、いつでも復習できる、非公開で検索可能な一か所です。",
    ""
  ]
};

const TABLE: Record<Locale, NotebookLabels> = {
  en,
  "zh-cn": zhCn,
  "zh-tw": zhTw,
  ja
};

export function notebookLabels(locale: Locale = "en"): NotebookLabels {
  return TABLE[locale] ?? en;
}
